version: "3.8"
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - config.env
    command: minio server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
